package mx.com.meda;

public enum Socio{
	BABY_TOWN("BABY TOWN", 1),
	BASIC_PUFF("BASIC PUFF", 2),
	BIOMEDICA_DE_REFERENCIA("BIOMEDICA DE REFERENCIA", 3),
	CHEDRAUI("CHEDRAUI", 4),
	CIRCULO_K("CIRCULO K", 5),
	CROSSFIT_RAM("CROSSFIT RAM", 6),
	DENTALIA("DENTALIA", 7),
	ECO_SALADS("ECO SALADS", 8),
	EDUCANET_UVEM("EDUCANET - UVEM", 9),
	EL_CUEVON("EL CUEVON", 10),
	EL_SURTIDOR("EL SURTIDOR", 11),
	EPS_SERVICIO_AUTOMOTRIZ("EPS SERVICIO AUTOMOTRIZ", 12),
	ESTETICA_SHARM("ESTETICA SHARM", 13),
	FIESTA_AMERICANA("FIESTA AMERICANA", 14),
	FIESTA_AMERICANA_GRAND("FIESTA AMERICANA GRAND", 15),
	FIESTA_INN("FIESTA INN", 16),
	GREEN_LIGHT_GOURMET_PIZZA("GREEN LIGHT GOURMET PIZZA", 17),
	GYMBOREE("GYMBOREE", 18),
	HIDROSINA("HIDROSINA", 19),
	IAVE("IAVE", 20),
	IHOP("IHOP", 21),
	INMODA("INMODA", 22),
	JUGUETERIAS_JULIO_CEPEDA("JUGUETERIAS JULIO CEPEDA", 23),
	KINDERGYM("KINDERGYM", 24),
	LE_PARISIEN("LE PARISIEN", 25),
	LIBRERIAS_PORRUA("LIBRERIAS PORRUA", 26),
	LIVE_AQUA("LIVE AQUA", 27),
	MEXICAN_FOOD_TOURS("MEXICAN FOOD TOURS", 28),
	MULTIFARMACIAS("MULTIFARMACIAS", 29),
	MULTIFARMACIAS_GENERICOS("MULTIFARMACIAS GENERICOS", 30),
	ONE("ONE", 31),
	OSTAR("OSTAR", 32),
	PAKMAIL("PAKMAIL", 33),
	PUNTO_VERDE("PUNTO VERDE", 34),
	SUPERCOLCHONES("SUPERCOLCHONES", 35),
	THE_HAMBURGUER_CLUB("THE HAMBURGUER CLUB", 36),
	TIENDAS_ATLAS("TIENDAS ATLAS", 37),
	TINTORERIA_REAL("TINTORERIA REAL", 38),
	TUR_TUX("TUR TUX", 39),
	VIVE_GADGET("VIVE GADGET", 40),
	WA_TEPPAN_SUSHI_BAR("WA TEPPAN-SUSHI BAR", 41),
	WOK_INN("WOK INN", 42),
	TELCEL("TELCEL", 43),
	DECOMPRAS("DECOMPRAS", 44),
	SANBORNS("SANBORNS", 45),
	HITSS("HITSS", 46),
	HITSS_ACREDITACIONES("HITSS_ACREDITACIONES", 46),
	EL_TIZONCITO("EL TIZONCITO", 47),
	INBURSA("INBURSA", 52);

	private int id= 1;
	private String nombre;

	Socio(String nombre, int id) {
		this.id = id;
		this.nombre = nombre;
	}

	public int getId() {
		return this.id;
	}
	public String getNombre() {
		return this.nombre;
	}


}